version: '3.7'
services:
  dbpostgresql:
    image: postgres:latest
    container_name: postgres
    network_mode: bridge
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  molpadia_webapp:
    image: molpadia_webapp:latest
    container_name: molpadia_webapp
    network_mode: bridge
    depends_on:
      - dbpostgresql
    expose:
      - 8080
    ports:
      - 16500:8080
    links:
      - dbpostgresql
    volumes:
      - ./build/libs/:/tmp/build/libs/
    restart: unless-stopped

volumes:
  postgres-data:
